### ISSUE TITLE
vim-plug support

### ISSUE THREAD

**Issue by francois-pasquier** [zgpio/travis#6]
Hi, I wanted to give your plugin a try but I can't make it work with neovim plugin system.
Can you give us an ETA regarding this?

**Comment by zgpio** [comment]
Thanks for your feedback, sorry for taking so long to reply.
The current vim plugin system is a trick, the plugin manager does not support github release zip well, because tree.nvim needs to be compiled in order to use it. The method I can think of is to maintain a new repository through the automatic build system, but I temporarily No such plan.
